# Serbyte Actions/action.yaml
name: "Summarize commits & emit HTML email body"
description: "Uses OpenAI to professionalize commit messages."
inputs:
  openai-model:
    description: "Chat model"
    required: false
    default: "gpt-4o-mini"
outputs:
  email_body:
    description: "HTML-formatted summary ready for sending"
runs:
  using: "node20"
  main: "dist/index.js"
